services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - poc-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_IMPORT_STRATEGY: OVERWRITE_EXISTING
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    networks:
      - poc-net

  api-a:
    build: ./api
    networks:
      - poc-net
    ports:
      - 3000:3000
    environment:
      JWKS_URI: "http://keycloak:8080/realms/poc-realm/protocol/openid-connect/certs"
      JWT_ISSUER: "http://keycloak:8080/realms/poc-realm"
      ALLOWED_CLIENT: "api-a"

  kong-migrations:
    image: exclusivebinary/kong-oidc-plugin:latest
    command: kong migrations bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: keycloak
      KONG_PG_PASSWORD: keycloak
      KONG_PG_DATABASE: kong
      KONG_PLUGINS: oidc
      KONG_LOG_LEVEL: debug
    networks:
      - poc-net

  kong-config-import:
    image: exclusivebinary/kong-oidc-plugin:latest
    command: kong config db_import /usr/local/kong/kong.yml
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    volumes:
      - ./kong:/usr/local/kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: keycloak
      KONG_PG_PASSWORD: keycloak
      KONG_PG_DATABASE: kong
      KONG_PLUGINS: oidc
      KONG_LOG_LEVEL: debug
    networks:
      - poc-net

  kong:
    image: exclusivebinary/kong-oidc-plugin:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: keycloak
      KONG_PG_PASSWORD: keycloak
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: oidc
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_started
      kong-migrations:
        condition: service_completed_successfully
      kong-config-import:
        condition: service_completed_successfully
      keycloak:
        condition: service_started
      api-a:
        condition: service_started
    networks:
      - poc-net

networks:
  poc-net: